
name: CI

# Triggers the workflow on push to master
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Zip and upload to AWS S3
      run: |
        zip presence.zip lambda_function.py redis*
        aws s3 cp presence.zip s3://nordri-check-presence/presence.zip

    - name: Deploy Lambda function with CloudFormation
      run: |
        aws cloudformation create-stack \
          --stack-name check-presence-$GITHUB_RUN_NUMBER \
          --template-body file://Cloudformation.yaml \
          --parameters ParameterKey=LambdaVPCSubnet,ParameterValue=subnet-c3272585 \
                       ParameterKey=S3Bucket,ParameterValue=nordri-check-presence \
                       ParameterKey=VPCSecurityGroup,ParameterValue=sg-52559837
